version: "3"

services:
  julia:
    container_name: julia_service
    build: 
      context: .
    volumes: 
      - ".:/usr/src/"
    working_dir: /usr/src/
    environment:
      - TSP_FILE=${TSP_FILE}
    command: bash -c "julia src/main.jl"